remote_theme: pomocna-dlon/jekyll-cayman-pomocna-dlon
author: Pomocna Dłoń ([pomocnadlon12@interia.pl](mailto:pomocnadlon12@interia.pl))
title: "Jarosławska Fundacja Pomocna Dłoń"
logo: /img/layout/logo.png
show_downloads: false
description: " "
lang: pl-PL
menu_links: MenuLinks.html
github:
  is_project_page: false
